apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: nitesh1508/gitops01:99e58962601a484f5e0c3d20040ed3ba2330b1e4
          imagePullPolicy: Always
          ports:
            - containerPort: 80
